insert into healthreport_agents
values
(1,  'bacterium', 'Bordetella bronschiseptica', '', ''),
(2,  'bacterium', 'Citrobacter rodentium', '', ''),
(3,  'bacterium', 'Clostridium piliforme', '', ''),
(4,  'bacterium', 'Corynebacterium kutscheri', '', ''),
(5,  'bacterium', 'Helicobacter spp', '', ''),
(6,  'bacterium', 'Klebsiella spp.', '', ''),
(7,  'bacterium', 'Leptospira spp (ballum, canicola, hebdomanis, icterohaemorrhagiea', '', ''),
(8,  'bacterium', 'Mycoplasma pulmonis', '', ''),
(9,  'bacterium', 'Pasteurellaceae', '', ''),
(10, 'bacterium', 'Pseudomons spp.', '', ''),
(11, 'bacterium', 'Salmonellae', '', ''),
(12, 'bacterium', 'Streptobacillus moniliformis', '', ''),
(13, 'bacterium', 'beta-haemolytic streptococci', '', ''),
(14, 'bacterium', 'Streptococcus pneumoniae', '', ''),
(15, 'virus',     'Mouse adenovirus FL', '', ''),
(16, 'virus',     'Mouse adenovirus K87', '', ''),
(17, 'virus',     'Mouse hepatitis virus', '', ''),
(18, 'virus',     'Mouse K virus', '', ''),
(19, 'virus',     'Mouse rotavirus', '', ''),
(20, 'virus',     'Mouse parvovirus', '', ''),
(21, 'virus',     'Minute virus of mice', '', ''),
(22, 'virus',     'Pneumonia virus of mice', '', ''),
(23, 'virus',     'Reovirus type 3', '', ''),
(24, 'virus',     'Sendai virus', '', ''),
(25, 'virus',     'Theilers murine encephalomyelitis virus', '', ''),
(26, 'virus',     'Ectromelia virus', '', ''),
(27, 'virus',     'Hantvirus', '', ''),
(28, 'virus',     'Lactacte dehydrogenase virus', '', ''),
(29, 'virus',     'Lymphocytic choriomeningitis virus', '', ''),
(30, 'virus',     'Mouse cytomegalovirus', '', ''),
(31, 'virus',     'Mouse polyoma virus', '', ''),
(32, 'virus',     'Mouse thymic virus', '', ''),
(33, 'parasite',  'Arthropods (i.e. Myobia spp.)', '', ''),
(34, 'parasite',  'Eimeria spp.', '', ''),
(35, 'parasite',  'Entamoeba muris', '', ''),
(36, 'parasite',  'Gastrointestinal helminths (i.e. Syphacia spp.)', '', ''),
(37, 'parasite',  'Giardia spp.', '', ''),
(38, 'parasite',  'Klosiella spp.', '', ''),
(39, 'parasite',  'Protozoan flagellates (i.e. Enteromonas)', '', ''),
(40, 'parasite',  'Spironucleus spp.', '', '');

