INSERT INTO `death_reasons` VALUES (1,'how','alive',''),
(2,'why','alive',''),
(3,'how','killed',''),
(4,'how','found dead',''),
(5,'why','breeding excess',''),
(6,'why','unknown',''),
(7,'how','exported',''),
(8,'why','died in experiment',''),
(9,'why','exported',''),
(10,'why','organ withdrawal',''),
(11,'why','wrong genotype',''),
(12,'why','spermfreeze',''),
(13,'why','illness',''),
(14,'why','blood sample',''),
(15,'why','old',''),
(16,'why','drown',''),
(17,'why','tescreen',''),
(18,'why','manipulation',''),
(19,'why','prscreen',''),
(20,'why','sescreen',''),
(21,'why','not pregnant',NULL),
(22,'why','plug negative',NULL),
(23,'why','cryo archiving',NULL),
(24,'why','challenge screen',NULL);
